services:
  esscrypt-agent-db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: esscrypt-agent-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: esscrypt
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Stores data outside the container to ensure persistence